# tGri1 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[1]], "gri1", "vis1", verbose=TRUE)
# tGri2 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[2]], "gri2", "vis2", verbose=TRUE)
# tGri3 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[3]], "gri3", "vis3", verbose=TRUE)
# tGri4 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[4]], "gri4", "vis4", verbose=TRUE)
# tGri1.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gri1", "vis1", verbose=TRUE)
# tGri2.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gri2", "vis2", verbose=TRUE)
# tGri3.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gri3", "vis3", verbose=TRUE)
# tGri4.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gri4", "vis4", verbose=TRUE)
# 
# tGas1 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[1]], "gas1", "vis1", verbose=TRUE)
# tGas2 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[2]], "gas2", "vis2", verbose=TRUE)
# tGas3 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[3]], "gas3", "vis3", verbose=TRUE)
# tGas4 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpopAge[[4]], "gas4", "vis4", verbose=TRUE)
# tGas1.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gas1", "vis1", verbose=TRUE)
# tGas2.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gas2", "vis2", verbose=TRUE)
# tGas3.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gas3", "vis3", verbose=TRUE)
# tGas4.0 <- fitFluModel(subset(sentinelBig, yearweek<=tgtweek), NUTSpop, "gas4", "vis4", verbose=TRUE)

cairo_pdf("comparison.pdf", width=8.3, height=11.7, pointsize=8)
par(mfcol=c(4,2), oma=c(3,3,1,2))
plot(tGri1$gri, type="l", col="red", bty="l"); points(tGri1.0$gri, type="l", col="blue")
plot(tGri2$gri, type="l", col="red", bty="l"); points(tGri2.0$gri, type="l", col="blue")
plot(tGri3$gri, type="l", col="red", bty="l"); points(tGri3.0$gri, type="l", col="blue")
plot(tGri4$gri, type="l", col="red", bty="l"); points(tGri4.0$gri, type="l", col="blue")
plot(tGas1$gri, type="l", col="red", bty="l"); points(tGas1.0$gri, type="l", col="blue")
plot(tGas2$gri, type="l", col="red", bty="l"); points(tGas2.0$gri, type="l", col="blue")
plot(tGas3$gri, type="l", col="red", bty="l"); points(tGas3.0$gri, type="l", col="blue")
plot(tGas4$gri, type="l", col="red", bty="l"); points(tGas4.0$gri, type="l", col="blue")
dev.off()
